-- 코드를 입력하세요
SELECT c.CAR_ID, c.CAR_TYPE, ROUND((c.DAILY_FEE * 30) * (100 - p.DISCOUNT_RATE) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_RENTAL_HISTORY h, CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
WHERE c.CAR_ID = h.CAR_ID AND c.CAR_TYPE = p.CAR_TYPE
AND c.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND p.DURATION_TYPE = '30일 이상'
AND c.CAR_TYPE IN ('세단', 'SUV')
GROUP BY c.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;