SELECT 
    I.REST_ID,
    I.REST_NAME,
    FOOD_TYPE,FAVORITES,ADDRESS,
    ROUND(AVG(REVIEW_SCORE),2) SCORE
from REST_INFO I , REST_REVIEW R

where 
    I.REST_ID = R.REST_ID AND
    ADDRESS LIKE "서울%"
GROUP BY REST_ID

ORDER BY SCORE DESC,FAVORITES DESC